;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 15
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
;Peel sheet 2 relative to 0
;KS: Cast on 20loops from 0to 20
tuck - f57 1
tuck - f51 1
tuck - f45 1
tuck - f39 1
tuck - f33 1
tuck - f27 1
tuck - f21 1
tuck - f15 1
tuck - f9 1
tuck - f3 1
tuck + f0 1
tuck + f6 1
tuck + f12 1
tuck + f18 1
tuck + f24 1
tuck + f30 1
tuck + f36 1
tuck + f42 1
tuck + f48 1
tuck + f54 1
tuck - f57 1
tuck - f51 1
tuck - f45 1
tuck - f39 1
tuck - f33 1
tuck - f27 1
tuck - f21 1
tuck - f15 1
tuck - f9 1
tuck - f3 1
tuck + f0 1
tuck + f6 1
tuck + f12 1
tuck + f18 1
tuck + f24 1
tuck + f30 1
tuck + f36 1
tuck + f42 1
tuck + f48 1
tuck + f54 1
releasehook 1
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
;KS: Cast on 20loops from 0to 20
tuck - f58 1
tuck - f52 1
tuck - f46 1
tuck - f40 1
tuck - f34 1
tuck - f28 1
tuck - f22 1
tuck - f16 1
tuck - f10 1
tuck - f4 1
tuck + f1 1
tuck + f7 1
tuck + f13 1
tuck + f19 1
tuck + f25 1
tuck + f31 1
tuck + f37 1
tuck + f43 1
tuck + f49 1
tuck + f55 1
tuck - f58 1
tuck - f52 1
tuck - f46 1
tuck - f40 1
tuck - f34 1
tuck - f28 1
tuck - f22 1
tuck - f16 1
tuck - f10 1
tuck - f4 1
tuck + f1 1
tuck + f7 1
tuck + f13 1
tuck + f19 1
tuck + f25 1
tuck + f31 1
tuck + f37 1
tuck + f43 1
tuck + f49 1
tuck + f55 1
;no-op. Releasehook with no hooked carriers
knit - f58 1
knit - f55 1
knit - f52 1
knit - f49 1
knit - f46 1
knit - f43 1
knit - f40 1
knit - f37 1
knit - f34 1
knit - f31 1
knit - f28 1
knit - f25 1
knit - f22 1
knit - f19 1
knit - f16 1
knit - f13 1
knit - f10 1
knit - f7 1
knit - f4 1
knit - f1 1
knit + f1 1
knit + f4 1
knit + f7 1
knit + f10 1
knit + f13 1
knit + f16 1
knit + f19 1
knit + f22 1
knit + f25 1
knit + f28 1
knit + f31 1
knit + f34 1
knit + f37 1
knit + f40 1
knit + f43 1
knit + f46 1
knit + f49 1
knit + f52 1
knit + f55 1
knit + f58 1
knit - f58 1
knit - f55 1
knit - f52 1
knit - f49 1
knit - f46 1
knit - f43 1
knit - f40 1
knit - f37 1
knit - f34 1
knit - f31 1
knit - f28 1
knit - f25 1
knit - f22 1
knit - f19 1
knit - f16 1
knit - f13 1
knit - f10 1
knit - f7 1
knit - f4 1
knit - f1 1
knit + f1 1
knit + f4 1
knit + f7 1
knit + f10 1
knit + f13 1
knit + f16 1
knit + f19 1
knit + f22 1
knit + f25 1
knit + f28 1
knit + f31 1
knit + f34 1
knit + f37 1
knit + f40 1
knit + f43 1
knit + f46 1
knit + f49 1
knit + f52 1
knit + f55 1
knit + f58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
;Peel sheet 2 relative to 2
;KS: Cast on 20loops from 0to 20
tuck - f59 1
tuck - f53 1
tuck - f47 1
tuck - f41 1
tuck - f35 1
tuck - f29 1
tuck - f23 1
tuck - f17 1
tuck - f11 1
tuck - f5 1
tuck + f2 1
tuck + f8 1
tuck + f14 1
tuck + f20 1
tuck + f26 1
tuck + f32 1
tuck + f38 1
tuck + f44 1
tuck + f50 1
tuck + f56 1
tuck - f59 1
tuck - f53 1
tuck - f47 1
tuck - f41 1
tuck - f35 1
tuck - f29 1
tuck - f23 1
tuck - f17 1
tuck - f11 1
tuck - f5 1
tuck + f2 1
tuck + f8 1
tuck + f14 1
tuck + f20 1
tuck + f26 1
tuck + f32 1
tuck + f38 1
tuck + f44 1
tuck + f50 1
tuck + f56 1
;no-op. Releasehook with no hooked carriers
knit - f59 1
knit - f56 1
knit - f53 1
knit - f50 1
knit - f47 1
knit - f44 1
knit - f41 1
knit - f38 1
knit - f35 1
knit - f32 1
knit - f29 1
knit - f26 1
knit - f23 1
knit - f20 1
knit - f17 1
knit - f14 1
knit - f11 1
knit - f8 1
knit - f5 1
knit - f2 1
knit + f2 1
knit + f5 1
knit + f8 1
knit + f11 1
knit + f14 1
knit + f17 1
knit + f20 1
knit + f23 1
knit + f26 1
knit + f29 1
knit + f32 1
knit + f35 1
knit + f38 1
knit + f41 1
knit + f44 1
knit + f47 1
knit + f50 1
knit + f53 1
knit + f56 1
knit + f59 1
knit - f59 1
knit - f56 1
knit - f53 1
knit - f50 1
knit - f47 1
knit - f44 1
knit - f41 1
knit - f38 1
knit - f35 1
knit - f32 1
knit - f29 1
knit - f26 1
knit - f23 1
knit - f20 1
knit - f17 1
knit - f14 1
knit - f11 1
knit - f8 1
knit - f5 1
knit - f2 1
knit + f2 1
knit + f5 1
knit + f8 1
knit + f11 1
knit + f14 1
knit + f17 1
knit + f20 1
knit + f23 1
knit + f26 1
knit + f29 1
knit + f32 1
knit + f35 1
knit + f38 1
knit + f41 1
knit + f44 1
knit + f47 1
knit + f50 1
knit + f53 1
knit + f56 1
knit + f59 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer f2 b2;peel loops [340 on yarn 1] from s2 relative to s1
xfer f5 b5;peel loops [341 on yarn 1] from s2 relative to s1
xfer f8 b8;peel loops [342 on yarn 1] from s2 relative to s1
xfer f11 b11;peel loops [343 on yarn 1] from s2 relative to s1
xfer f14 b14;peel loops [344 on yarn 1] from s2 relative to s1
xfer f17 b17;peel loops [345 on yarn 1] from s2 relative to s1
xfer f20 b20;peel loops [346 on yarn 1] from s2 relative to s1
xfer f23 b23;peel loops [347 on yarn 1] from s2 relative to s1
xfer f26 b26;peel loops [348 on yarn 1] from s2 relative to s1
xfer f29 b29;peel loops [349 on yarn 1] from s2 relative to s1
xfer f32 b32;peel loops [350 on yarn 1] from s2 relative to s1
xfer f35 b35;peel loops [351 on yarn 1] from s2 relative to s1
xfer f38 b38;peel loops [352 on yarn 1] from s2 relative to s1
xfer f41 b41;peel loops [353 on yarn 1] from s2 relative to s1
xfer f44 b44;peel loops [354 on yarn 1] from s2 relative to s1
xfer f47 b47;peel loops [355 on yarn 1] from s2 relative to s1
xfer f50 b50;peel loops [356 on yarn 1] from s2 relative to s1
xfer f53 b53;peel loops [357 on yarn 1] from s2 relative to s1
xfer f56 b56;peel loops [358 on yarn 1] from s2 relative to s1
xfer f59 b59;peel loops [359 on yarn 1] from s2 relative to s1
xfer f58 b58
xfer f55 b55
xfer f46 b46
xfer f43 b43
xfer f34 b34
xfer f31 b31
xfer f22 b22
xfer f19 b19
xfer f10 b10
xfer f7 b7
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [222 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [223 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [226 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [227 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [230 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [231 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [234 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [235 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [238 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [239 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
xfer b2 f2;return loops [340 on yarn 1]
xfer b5 f5;return loops [341 on yarn 1]
xfer b8 f8;return loops [342 on yarn 1]
xfer b11 f11;return loops [343 on yarn 1]
xfer b14 f14;return loops [344 on yarn 1]
xfer b17 f17;return loops [345 on yarn 1]
xfer b20 f20;return loops [346 on yarn 1]
xfer b23 f23;return loops [347 on yarn 1]
xfer b26 f26;return loops [348 on yarn 1]
xfer b29 f29;return loops [349 on yarn 1]
xfer b32 f32;return loops [350 on yarn 1]
xfer b35 f35;return loops [351 on yarn 1]
xfer b38 f38;return loops [352 on yarn 1]
xfer b41 f41;return loops [353 on yarn 1]
xfer b44 f44;return loops [354 on yarn 1]
xfer b47 f47;return loops [355 on yarn 1]
xfer b50 f50;return loops [356 on yarn 1]
xfer b53 f53;return loops [357 on yarn 1]
xfer b56 f56;return loops [358 on yarn 1]
xfer b59 f59;return loops [359 on yarn 1]
xfer f59 b59
xfer f56 b56
xfer f53 b53
xfer f50 b50
xfer f47 b47
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [220 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [221 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [222 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [223 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [224 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [225 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [226 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [227 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [228 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [229 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [230 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [231 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [232 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [233 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [234 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [235 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [236 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [237 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [238 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [239 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [220 on yarn 1]
xfer b4 f4;return loops [221 on yarn 1]
xfer b13 f13;return loops [224 on yarn 1]
xfer b16 f16;return loops [225 on yarn 1]
xfer b25 f25;return loops [228 on yarn 1]
xfer b28 f28;return loops [229 on yarn 1]
xfer b37 f37;return loops [232 on yarn 1]
xfer b40 f40;return loops [233 on yarn 1]
xfer b49 f49;return loops [236 on yarn 1]
xfer b52 f52;return loops [237 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [382 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [383 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [386 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [387 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [390 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [391 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [394 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [395 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [398 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [399 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [380 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [381 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [382 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [383 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [384 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [385 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [386 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [387 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [388 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [389 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [390 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [391 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [392 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [393 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [394 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [395 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [396 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [397 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [398 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [399 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [380 on yarn 1]
xfer b4 f4;return loops [381 on yarn 1]
xfer b13 f13;return loops [384 on yarn 1]
xfer b16 f16;return loops [385 on yarn 1]
xfer b25 f25;return loops [388 on yarn 1]
xfer b28 f28;return loops [389 on yarn 1]
xfer b37 f37;return loops [392 on yarn 1]
xfer b40 f40;return loops [393 on yarn 1]
xfer b49 f49;return loops [396 on yarn 1]
xfer b52 f52;return loops [397 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [457 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [456 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [453 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [452 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [449 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [448 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [445 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [444 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [441 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [440 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [459 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [458 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [457 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [456 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [455 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [454 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [453 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [452 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [451 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [450 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [449 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [448 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [447 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [446 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [445 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [444 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [443 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [442 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [441 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [440 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [459 on yarn 1]
xfer b4 f4;return loops [458 on yarn 1]
xfer b13 f13;return loops [455 on yarn 1]
xfer b16 f16;return loops [454 on yarn 1]
xfer b25 f25;return loops [451 on yarn 1]
xfer b28 f28;return loops [450 on yarn 1]
xfer b37 f37;return loops [447 on yarn 1]
xfer b40 f40;return loops [446 on yarn 1]
xfer b49 f49;return loops [443 on yarn 1]
xfer b52 f52;return loops [442 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [502 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [503 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [506 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [507 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [510 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [511 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [514 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [515 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [518 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [519 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [500 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [501 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [502 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [503 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [504 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [505 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [506 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [507 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [508 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [509 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [510 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [511 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [512 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [513 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [514 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [515 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [516 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [517 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [518 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [519 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [500 on yarn 1]
xfer b4 f4;return loops [501 on yarn 1]
xfer b13 f13;return loops [504 on yarn 1]
xfer b16 f16;return loops [505 on yarn 1]
xfer b25 f25;return loops [508 on yarn 1]
xfer b28 f28;return loops [509 on yarn 1]
xfer b37 f37;return loops [512 on yarn 1]
xfer b40 f40;return loops [513 on yarn 1]
xfer b49 f49;return loops [516 on yarn 1]
xfer b52 f52;return loops [517 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [577 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [576 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [573 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [572 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [569 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [568 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [565 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [564 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [561 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [560 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [579 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [578 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [577 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [576 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [575 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [574 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [573 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [572 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [571 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [570 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [569 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [568 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [567 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [566 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [565 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [564 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [563 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [562 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [561 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [560 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [579 on yarn 1]
xfer b4 f4;return loops [578 on yarn 1]
xfer b13 f13;return loops [575 on yarn 1]
xfer b16 f16;return loops [574 on yarn 1]
xfer b25 f25;return loops [571 on yarn 1]
xfer b28 f28;return loops [570 on yarn 1]
xfer b37 f37;return loops [567 on yarn 1]
xfer b40 f40;return loops [566 on yarn 1]
xfer b49 f49;return loops [563 on yarn 1]
xfer b52 f52;return loops [562 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [622 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [623 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [626 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [627 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [630 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [631 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [634 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [635 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [638 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [639 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [620 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [621 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [622 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [623 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [624 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [625 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [626 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [627 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [628 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [629 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [630 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [631 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [632 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [633 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [634 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [635 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [636 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [637 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [638 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [639 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [620 on yarn 1]
xfer b4 f4;return loops [621 on yarn 1]
xfer b13 f13;return loops [624 on yarn 1]
xfer b16 f16;return loops [625 on yarn 1]
xfer b25 f25;return loops [628 on yarn 1]
xfer b28 f28;return loops [629 on yarn 1]
xfer b37 f37;return loops [632 on yarn 1]
xfer b40 f40;return loops [633 on yarn 1]
xfer b49 f49;return loops [636 on yarn 1]
xfer b52 f52;return loops [637 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [697 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [696 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [693 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [692 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [689 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [688 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [685 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [684 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [681 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [680 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [699 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [698 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [697 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [696 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [695 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [694 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [693 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [692 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [691 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [690 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [689 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [688 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [687 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [686 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [685 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [684 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [683 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [682 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [681 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [680 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [699 on yarn 1]
xfer b4 f4;return loops [698 on yarn 1]
xfer b13 f13;return loops [695 on yarn 1]
xfer b16 f16;return loops [694 on yarn 1]
xfer b25 f25;return loops [691 on yarn 1]
xfer b28 f28;return loops [690 on yarn 1]
xfer b37 f37;return loops [687 on yarn 1]
xfer b40 f40;return loops [686 on yarn 1]
xfer b49 f49;return loops [683 on yarn 1]
xfer b52 f52;return loops [682 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [742 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [743 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [746 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [747 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [750 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [751 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [754 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [755 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [758 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [759 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [740 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [741 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [742 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [743 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [744 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [745 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [746 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [747 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [748 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [749 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [750 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [751 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [752 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [753 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [754 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [755 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [756 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [757 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [758 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [759 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [740 on yarn 1]
xfer b4 f4;return loops [741 on yarn 1]
xfer b13 f13;return loops [744 on yarn 1]
xfer b16 f16;return loops [745 on yarn 1]
xfer b25 f25;return loops [748 on yarn 1]
xfer b28 f28;return loops [749 on yarn 1]
xfer b37 f37;return loops [752 on yarn 1]
xfer b40 f40;return loops [753 on yarn 1]
xfer b49 f49;return loops [756 on yarn 1]
xfer b52 f52;return loops [757 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [817 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [816 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [813 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [812 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [809 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [808 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [805 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [804 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [801 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [800 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [819 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [818 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [817 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [816 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [815 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [814 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [813 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [812 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [811 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [810 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [809 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [808 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [807 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [806 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [805 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [804 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [803 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [802 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [801 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [800 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [819 on yarn 1]
xfer b4 f4;return loops [818 on yarn 1]
xfer b13 f13;return loops [815 on yarn 1]
xfer b16 f16;return loops [814 on yarn 1]
xfer b25 f25;return loops [811 on yarn 1]
xfer b28 f28;return loops [810 on yarn 1]
xfer b37 f37;return loops [807 on yarn 1]
xfer b40 f40;return loops [806 on yarn 1]
xfer b49 f49;return loops [803 on yarn 1]
xfer b52 f52;return loops [802 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [862 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [863 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [866 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [867 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [870 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [871 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [874 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [875 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [878 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [879 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [860 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [861 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [862 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [863 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [864 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [865 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [866 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [867 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [868 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [869 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [870 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [871 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [872 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [873 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [874 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [875 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [876 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [877 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [878 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [879 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [860 on yarn 1]
xfer b4 f4;return loops [861 on yarn 1]
xfer b13 f13;return loops [864 on yarn 1]
xfer b16 f16;return loops [865 on yarn 1]
xfer b25 f25;return loops [868 on yarn 1]
xfer b28 f28;return loops [869 on yarn 1]
xfer b37 f37;return loops [872 on yarn 1]
xfer b40 f40;return loops [873 on yarn 1]
xfer b49 f49;return loops [876 on yarn 1]
xfer b52 f52;return loops [877 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [937 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [936 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [933 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [932 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [929 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [928 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [925 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [924 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [921 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [920 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [939 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [938 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [937 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [936 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [935 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [934 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [933 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [932 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [931 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [930 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [929 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [928 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [927 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [926 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [925 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [924 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [923 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [922 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [921 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [920 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [939 on yarn 1]
xfer b4 f4;return loops [938 on yarn 1]
xfer b13 f13;return loops [935 on yarn 1]
xfer b16 f16;return loops [934 on yarn 1]
xfer b25 f25;return loops [931 on yarn 1]
xfer b28 f28;return loops [930 on yarn 1]
xfer b37 f37;return loops [927 on yarn 1]
xfer b40 f40;return loops [926 on yarn 1]
xfer b49 f49;return loops [923 on yarn 1]
xfer b52 f52;return loops [922 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [982 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [983 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [986 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [987 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [990 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [991 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [994 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [995 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [998 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [999 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [980 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [981 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [982 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [983 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [984 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [985 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [986 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [987 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [988 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [989 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [990 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [991 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [992 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [993 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [994 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [995 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [996 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [997 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [998 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [999 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [980 on yarn 1]
xfer b4 f4;return loops [981 on yarn 1]
xfer b13 f13;return loops [984 on yarn 1]
xfer b16 f16;return loops [985 on yarn 1]
xfer b25 f25;return loops [988 on yarn 1]
xfer b28 f28;return loops [989 on yarn 1]
xfer b37 f37;return loops [992 on yarn 1]
xfer b40 f40;return loops [993 on yarn 1]
xfer b49 f49;return loops [996 on yarn 1]
xfer b52 f52;return loops [997 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1057 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1056 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1053 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1052 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1049 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1048 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1045 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1044 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1041 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1040 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1059 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1058 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1057 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1056 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1055 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1054 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1053 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1052 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1051 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1050 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1049 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1048 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1047 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1046 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1045 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1044 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1043 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1042 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1041 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1040 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1059 on yarn 1]
xfer b4 f4;return loops [1058 on yarn 1]
xfer b13 f13;return loops [1055 on yarn 1]
xfer b16 f16;return loops [1054 on yarn 1]
xfer b25 f25;return loops [1051 on yarn 1]
xfer b28 f28;return loops [1050 on yarn 1]
xfer b37 f37;return loops [1047 on yarn 1]
xfer b40 f40;return loops [1046 on yarn 1]
xfer b49 f49;return loops [1043 on yarn 1]
xfer b52 f52;return loops [1042 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1102 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1103 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1106 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1107 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1110 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1111 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1114 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1115 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1118 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1119 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1100 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1101 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1102 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1103 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1104 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1105 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1106 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1107 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1108 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1109 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1110 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1111 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1112 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1113 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1114 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1115 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1116 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1117 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1118 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1119 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1100 on yarn 1]
xfer b4 f4;return loops [1101 on yarn 1]
xfer b13 f13;return loops [1104 on yarn 1]
xfer b16 f16;return loops [1105 on yarn 1]
xfer b25 f25;return loops [1108 on yarn 1]
xfer b28 f28;return loops [1109 on yarn 1]
xfer b37 f37;return loops [1112 on yarn 1]
xfer b40 f40;return loops [1113 on yarn 1]
xfer b49 f49;return loops [1116 on yarn 1]
xfer b52 f52;return loops [1117 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1177 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1176 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1173 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1172 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1169 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1168 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1165 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1164 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1161 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1160 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1179 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1178 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1177 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1176 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1175 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1174 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1173 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1172 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1171 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1170 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1169 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1168 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1167 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1166 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1165 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1164 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1163 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1162 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1161 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1160 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1179 on yarn 1]
xfer b4 f4;return loops [1178 on yarn 1]
xfer b13 f13;return loops [1175 on yarn 1]
xfer b16 f16;return loops [1174 on yarn 1]
xfer b25 f25;return loops [1171 on yarn 1]
xfer b28 f28;return loops [1170 on yarn 1]
xfer b37 f37;return loops [1167 on yarn 1]
xfer b40 f40;return loops [1166 on yarn 1]
xfer b49 f49;return loops [1163 on yarn 1]
xfer b52 f52;return loops [1162 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1222 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1223 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1226 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1227 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1230 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1231 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1234 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1235 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1238 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1239 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1220 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1221 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1222 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1223 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1224 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1225 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1226 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1227 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1228 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1229 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1230 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1231 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1232 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1233 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1234 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1235 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1236 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1237 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1238 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1239 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1220 on yarn 1]
xfer b4 f4;return loops [1221 on yarn 1]
xfer b13 f13;return loops [1224 on yarn 1]
xfer b16 f16;return loops [1225 on yarn 1]
xfer b25 f25;return loops [1228 on yarn 1]
xfer b28 f28;return loops [1229 on yarn 1]
xfer b37 f37;return loops [1232 on yarn 1]
xfer b40 f40;return loops [1233 on yarn 1]
xfer b49 f49;return loops [1236 on yarn 1]
xfer b52 f52;return loops [1237 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1297 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1296 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1293 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1292 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1289 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1288 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1285 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1284 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1281 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1280 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1299 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1298 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1297 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1296 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1295 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1294 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1293 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1292 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1291 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1290 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1289 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1288 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1287 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1286 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1285 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1284 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1283 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1282 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1281 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1280 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1299 on yarn 1]
xfer b4 f4;return loops [1298 on yarn 1]
xfer b13 f13;return loops [1295 on yarn 1]
xfer b16 f16;return loops [1294 on yarn 1]
xfer b25 f25;return loops [1291 on yarn 1]
xfer b28 f28;return loops [1290 on yarn 1]
xfer b37 f37;return loops [1287 on yarn 1]
xfer b40 f40;return loops [1286 on yarn 1]
xfer b49 f49;return loops [1283 on yarn 1]
xfer b52 f52;return loops [1282 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1342 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1343 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1346 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1347 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1350 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1351 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1354 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1355 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1358 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1359 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1340 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1341 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1342 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1343 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1344 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1345 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1346 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1347 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1348 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1349 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1350 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1351 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1352 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1353 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1354 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1355 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1356 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1357 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1358 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1359 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1340 on yarn 1]
xfer b4 f4;return loops [1341 on yarn 1]
xfer b13 f13;return loops [1344 on yarn 1]
xfer b16 f16;return loops [1345 on yarn 1]
xfer b25 f25;return loops [1348 on yarn 1]
xfer b28 f28;return loops [1349 on yarn 1]
xfer b37 f37;return loops [1352 on yarn 1]
xfer b40 f40;return loops [1353 on yarn 1]
xfer b49 f49;return loops [1356 on yarn 1]
xfer b52 f52;return loops [1357 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1417 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1416 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1413 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1412 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1409 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1408 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1405 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1404 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1401 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1400 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1419 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1418 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1417 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1416 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1415 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1414 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1413 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1412 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1411 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1410 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1409 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1408 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1407 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1406 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1405 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1404 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1403 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1402 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1401 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1400 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1419 on yarn 1]
xfer b4 f4;return loops [1418 on yarn 1]
xfer b13 f13;return loops [1415 on yarn 1]
xfer b16 f16;return loops [1414 on yarn 1]
xfer b25 f25;return loops [1411 on yarn 1]
xfer b28 f28;return loops [1410 on yarn 1]
xfer b37 f37;return loops [1407 on yarn 1]
xfer b40 f40;return loops [1406 on yarn 1]
xfer b49 f49;return loops [1403 on yarn 1]
xfer b52 f52;return loops [1402 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1462 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1463 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1466 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1467 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1470 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1471 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1474 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1475 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1478 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1479 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1460 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1461 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1462 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1463 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1464 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1465 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1466 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1467 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1468 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1469 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1470 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1471 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1472 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1473 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1474 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1475 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1476 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1477 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1478 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1479 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1460 on yarn 1]
xfer b4 f4;return loops [1461 on yarn 1]
xfer b13 f13;return loops [1464 on yarn 1]
xfer b16 f16;return loops [1465 on yarn 1]
xfer b25 f25;return loops [1468 on yarn 1]
xfer b28 f28;return loops [1469 on yarn 1]
xfer b37 f37;return loops [1472 on yarn 1]
xfer b40 f40;return loops [1473 on yarn 1]
xfer b49 f49;return loops [1476 on yarn 1]
xfer b52 f52;return loops [1477 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1537 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1536 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1533 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1532 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1529 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1528 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1525 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1524 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1521 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1520 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1539 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1538 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1537 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1536 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1535 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1534 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1533 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1532 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1531 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1530 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1529 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1528 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1527 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1526 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1525 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1524 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1523 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1522 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1521 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1520 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1539 on yarn 1]
xfer b4 f4;return loops [1538 on yarn 1]
xfer b13 f13;return loops [1535 on yarn 1]
xfer b16 f16;return loops [1534 on yarn 1]
xfer b25 f25;return loops [1531 on yarn 1]
xfer b28 f28;return loops [1530 on yarn 1]
xfer b37 f37;return loops [1527 on yarn 1]
xfer b40 f40;return loops [1526 on yarn 1]
xfer b49 f49;return loops [1523 on yarn 1]
xfer b52 f52;return loops [1522 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1582 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1583 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1586 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1587 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1590 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1591 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1594 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1595 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1598 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1599 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1580 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1581 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1582 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1583 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1584 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1585 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1586 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1587 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1588 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1589 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1590 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1591 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1592 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1593 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1594 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1595 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1596 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1597 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1598 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1599 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1580 on yarn 1]
xfer b4 f4;return loops [1581 on yarn 1]
xfer b13 f13;return loops [1584 on yarn 1]
xfer b16 f16;return loops [1585 on yarn 1]
xfer b25 f25;return loops [1588 on yarn 1]
xfer b28 f28;return loops [1589 on yarn 1]
xfer b37 f37;return loops [1592 on yarn 1]
xfer b40 f40;return loops [1593 on yarn 1]
xfer b49 f49;return loops [1596 on yarn 1]
xfer b52 f52;return loops [1597 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1657 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1656 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1653 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1652 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1649 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1648 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1645 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1644 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1641 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1640 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1659 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1658 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1657 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1656 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1655 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1654 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1653 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1652 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1651 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1650 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1649 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1648 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1647 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1646 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1645 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1644 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1643 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1642 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1641 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1640 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1659 on yarn 1]
xfer b4 f4;return loops [1658 on yarn 1]
xfer b13 f13;return loops [1655 on yarn 1]
xfer b16 f16;return loops [1654 on yarn 1]
xfer b25 f25;return loops [1651 on yarn 1]
xfer b28 f28;return loops [1650 on yarn 1]
xfer b37 f37;return loops [1647 on yarn 1]
xfer b40 f40;return loops [1646 on yarn 1]
xfer b49 f49;return loops [1643 on yarn 1]
xfer b52 f52;return loops [1642 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1702 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1703 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1706 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1707 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1710 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1711 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1714 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1715 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1718 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1719 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1700 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1701 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1702 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1703 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1704 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1705 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1706 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1707 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1708 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1709 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1710 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1711 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1712 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1713 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1714 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1715 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1716 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1717 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1718 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1719 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1700 on yarn 1]
xfer b4 f4;return loops [1701 on yarn 1]
xfer b13 f13;return loops [1704 on yarn 1]
xfer b16 f16;return loops [1705 on yarn 1]
xfer b25 f25;return loops [1708 on yarn 1]
xfer b28 f28;return loops [1709 on yarn 1]
xfer b37 f37;return loops [1712 on yarn 1]
xfer b40 f40;return loops [1713 on yarn 1]
xfer b49 f49;return loops [1716 on yarn 1]
xfer b52 f52;return loops [1717 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1777 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1776 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1773 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1772 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1769 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1768 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1765 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1764 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1761 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1760 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1779 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1778 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1777 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1776 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1775 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1774 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1773 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1772 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1771 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1770 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1769 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1768 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1767 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1766 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1765 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1764 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1763 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1762 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1761 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1760 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1779 on yarn 1]
xfer b4 f4;return loops [1778 on yarn 1]
xfer b13 f13;return loops [1775 on yarn 1]
xfer b16 f16;return loops [1774 on yarn 1]
xfer b25 f25;return loops [1771 on yarn 1]
xfer b28 f28;return loops [1770 on yarn 1]
xfer b37 f37;return loops [1767 on yarn 1]
xfer b40 f40;return loops [1766 on yarn 1]
xfer b49 f49;return loops [1763 on yarn 1]
xfer b52 f52;return loops [1762 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1822 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1823 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1826 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1827 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1830 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1831 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1834 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1835 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1838 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1839 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1820 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1821 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1822 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1823 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1824 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1825 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1826 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1827 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1828 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1829 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1830 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1831 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1832 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1833 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1834 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1835 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1836 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1837 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1838 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1839 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1820 on yarn 1]
xfer b4 f4;return loops [1821 on yarn 1]
xfer b13 f13;return loops [1824 on yarn 1]
xfer b16 f16;return loops [1825 on yarn 1]
xfer b25 f25;return loops [1828 on yarn 1]
xfer b28 f28;return loops [1829 on yarn 1]
xfer b37 f37;return loops [1832 on yarn 1]
xfer b40 f40;return loops [1833 on yarn 1]
xfer b49 f49;return loops [1836 on yarn 1]
xfer b52 f52;return loops [1837 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1897 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1896 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1893 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1892 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1889 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1888 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1885 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1884 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1881 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1880 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1899 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1898 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1897 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1896 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1895 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1894 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1893 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1892 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1891 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1890 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1889 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1888 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1887 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1886 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1885 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1884 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1883 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1882 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1881 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1880 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1899 on yarn 1]
xfer b4 f4;return loops [1898 on yarn 1]
xfer b13 f13;return loops [1895 on yarn 1]
xfer b16 f16;return loops [1894 on yarn 1]
xfer b25 f25;return loops [1891 on yarn 1]
xfer b28 f28;return loops [1890 on yarn 1]
xfer b37 f37;return loops [1887 on yarn 1]
xfer b40 f40;return loops [1886 on yarn 1]
xfer b49 f49;return loops [1883 on yarn 1]
xfer b52 f52;return loops [1882 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [1942 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [1943 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [1946 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [1947 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [1950 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [1951 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [1954 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [1955 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [1958 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [1959 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1940 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [1941 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1942 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [1943 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1944 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [1945 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1946 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [1947 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1948 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [1949 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1950 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [1951 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1952 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [1953 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1954 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [1955 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1956 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [1957 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1958 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [1959 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [1940 on yarn 1]
xfer b4 f4;return loops [1941 on yarn 1]
xfer b13 f13;return loops [1944 on yarn 1]
xfer b16 f16;return loops [1945 on yarn 1]
xfer b25 f25;return loops [1948 on yarn 1]
xfer b28 f28;return loops [1949 on yarn 1]
xfer b37 f37;return loops [1952 on yarn 1]
xfer b40 f40;return loops [1953 on yarn 1]
xfer b49 f49;return loops [1956 on yarn 1]
xfer b52 f52;return loops [1957 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2017 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2016 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2013 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2012 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2009 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2008 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2005 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2004 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2001 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2000 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2019 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2018 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2017 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2016 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2015 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2014 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2013 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2012 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2011 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2010 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2009 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2008 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2007 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2006 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2005 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2004 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2003 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2002 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2001 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2000 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2019 on yarn 1]
xfer b4 f4;return loops [2018 on yarn 1]
xfer b13 f13;return loops [2015 on yarn 1]
xfer b16 f16;return loops [2014 on yarn 1]
xfer b25 f25;return loops [2011 on yarn 1]
xfer b28 f28;return loops [2010 on yarn 1]
xfer b37 f37;return loops [2007 on yarn 1]
xfer b40 f40;return loops [2006 on yarn 1]
xfer b49 f49;return loops [2003 on yarn 1]
xfer b52 f52;return loops [2002 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2062 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2063 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2066 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2067 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2070 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2071 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2074 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2075 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2078 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2079 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2060 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2061 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2062 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2063 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2064 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2065 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2066 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2067 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2068 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2069 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2070 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2071 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2072 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2073 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2074 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2075 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2076 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2077 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2078 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2079 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2060 on yarn 1]
xfer b4 f4;return loops [2061 on yarn 1]
xfer b13 f13;return loops [2064 on yarn 1]
xfer b16 f16;return loops [2065 on yarn 1]
xfer b25 f25;return loops [2068 on yarn 1]
xfer b28 f28;return loops [2069 on yarn 1]
xfer b37 f37;return loops [2072 on yarn 1]
xfer b40 f40;return loops [2073 on yarn 1]
xfer b49 f49;return loops [2076 on yarn 1]
xfer b52 f52;return loops [2077 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2137 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2136 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2133 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2132 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2129 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2128 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2125 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2124 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2121 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2120 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2139 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2138 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2137 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2136 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2135 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2134 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2133 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2132 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2131 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2130 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2129 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2128 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2127 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2126 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2125 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2124 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2123 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2122 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2121 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2120 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2139 on yarn 1]
xfer b4 f4;return loops [2138 on yarn 1]
xfer b13 f13;return loops [2135 on yarn 1]
xfer b16 f16;return loops [2134 on yarn 1]
xfer b25 f25;return loops [2131 on yarn 1]
xfer b28 f28;return loops [2130 on yarn 1]
xfer b37 f37;return loops [2127 on yarn 1]
xfer b40 f40;return loops [2126 on yarn 1]
xfer b49 f49;return loops [2123 on yarn 1]
xfer b52 f52;return loops [2122 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2182 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2183 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2186 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2187 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2190 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2191 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2194 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2195 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2198 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2199 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2180 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2181 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2182 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2183 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2184 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2185 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2186 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2187 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2188 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2189 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2190 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2191 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2192 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2193 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2194 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2195 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2196 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2197 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2198 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2199 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2180 on yarn 1]
xfer b4 f4;return loops [2181 on yarn 1]
xfer b13 f13;return loops [2184 on yarn 1]
xfer b16 f16;return loops [2185 on yarn 1]
xfer b25 f25;return loops [2188 on yarn 1]
xfer b28 f28;return loops [2189 on yarn 1]
xfer b37 f37;return loops [2192 on yarn 1]
xfer b40 f40;return loops [2193 on yarn 1]
xfer b49 f49;return loops [2196 on yarn 1]
xfer b52 f52;return loops [2197 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2257 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2256 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2253 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2252 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2249 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2248 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2245 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2244 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2241 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2240 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2259 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2258 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2257 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2256 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2255 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2254 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2253 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2252 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2251 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2250 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2249 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2248 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2247 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2246 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2245 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2244 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2243 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2242 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2241 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2240 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2259 on yarn 1]
xfer b4 f4;return loops [2258 on yarn 1]
xfer b13 f13;return loops [2255 on yarn 1]
xfer b16 f16;return loops [2254 on yarn 1]
xfer b25 f25;return loops [2251 on yarn 1]
xfer b28 f28;return loops [2250 on yarn 1]
xfer b37 f37;return loops [2247 on yarn 1]
xfer b40 f40;return loops [2246 on yarn 1]
xfer b49 f49;return loops [2243 on yarn 1]
xfer b52 f52;return loops [2242 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2302 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2303 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2306 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2307 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2310 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2311 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2314 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2315 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2318 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2319 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2300 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2301 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2302 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2303 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2304 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2305 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2306 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2307 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2308 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2309 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2310 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2311 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2312 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2313 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2314 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2315 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2316 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2317 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2318 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2319 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2300 on yarn 1]
xfer b4 f4;return loops [2301 on yarn 1]
xfer b13 f13;return loops [2304 on yarn 1]
xfer b16 f16;return loops [2305 on yarn 1]
xfer b25 f25;return loops [2308 on yarn 1]
xfer b28 f28;return loops [2309 on yarn 1]
xfer b37 f37;return loops [2312 on yarn 1]
xfer b40 f40;return loops [2313 on yarn 1]
xfer b49 f49;return loops [2316 on yarn 1]
xfer b52 f52;return loops [2317 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2377 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2376 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2373 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2372 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2369 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2368 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2365 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2364 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2361 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2360 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2379 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2378 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2377 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2376 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2375 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2374 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2373 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2372 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2371 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2370 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2369 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2368 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2367 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2366 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2365 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2364 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2363 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2362 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2361 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2360 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2379 on yarn 1]
xfer b4 f4;return loops [2378 on yarn 1]
xfer b13 f13;return loops [2375 on yarn 1]
xfer b16 f16;return loops [2374 on yarn 1]
xfer b25 f25;return loops [2371 on yarn 1]
xfer b28 f28;return loops [2370 on yarn 1]
xfer b37 f37;return loops [2367 on yarn 1]
xfer b40 f40;return loops [2366 on yarn 1]
xfer b49 f49;return loops [2363 on yarn 1]
xfer b52 f52;return loops [2362 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2422 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2423 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2426 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2427 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2430 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2431 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2434 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2435 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2438 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2439 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2420 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2421 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2422 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2423 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2424 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2425 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2426 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2427 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2428 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2429 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2430 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2431 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2432 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2433 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2434 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2435 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2436 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2437 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2438 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2439 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2420 on yarn 1]
xfer b4 f4;return loops [2421 on yarn 1]
xfer b13 f13;return loops [2424 on yarn 1]
xfer b16 f16;return loops [2425 on yarn 1]
xfer b25 f25;return loops [2428 on yarn 1]
xfer b28 f28;return loops [2429 on yarn 1]
xfer b37 f37;return loops [2432 on yarn 1]
xfer b40 f40;return loops [2433 on yarn 1]
xfer b49 f49;return loops [2436 on yarn 1]
xfer b52 f52;return loops [2437 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2497 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2496 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2493 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2492 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2489 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2488 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2485 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2484 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2481 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2480 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2499 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2498 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2497 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2496 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2495 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2494 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2493 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2492 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2491 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2490 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2489 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2488 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2487 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2486 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2485 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2484 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2483 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2482 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2481 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2480 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2499 on yarn 1]
xfer b4 f4;return loops [2498 on yarn 1]
xfer b13 f13;return loops [2495 on yarn 1]
xfer b16 f16;return loops [2494 on yarn 1]
xfer b25 f25;return loops [2491 on yarn 1]
xfer b28 f28;return loops [2490 on yarn 1]
xfer b37 f37;return loops [2487 on yarn 1]
xfer b40 f40;return loops [2486 on yarn 1]
xfer b49 f49;return loops [2483 on yarn 1]
xfer b52 f52;return loops [2482 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2542 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2543 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2546 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2547 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2550 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2551 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2554 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2555 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2558 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2559 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2540 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2541 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2542 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2543 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2544 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2545 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2546 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2547 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2548 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2549 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2550 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2551 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2552 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2553 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2554 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2555 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2556 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2557 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2558 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2559 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2540 on yarn 1]
xfer b4 f4;return loops [2541 on yarn 1]
xfer b13 f13;return loops [2544 on yarn 1]
xfer b16 f16;return loops [2545 on yarn 1]
xfer b25 f25;return loops [2548 on yarn 1]
xfer b28 f28;return loops [2549 on yarn 1]
xfer b37 f37;return loops [2552 on yarn 1]
xfer b40 f40;return loops [2553 on yarn 1]
xfer b49 f49;return loops [2556 on yarn 1]
xfer b52 f52;return loops [2557 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2617 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2616 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2613 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2612 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2609 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2608 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2605 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2604 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2601 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2600 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2619 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2618 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2617 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2616 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2615 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2614 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2613 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2612 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2611 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2610 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2609 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2608 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2607 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2606 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2605 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2604 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2603 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2602 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2601 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2600 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit - f57 1
knit - f54 1
knit - f51 1
knit - f48 1
knit - f45 1
knit - f42 1
knit - f39 1
knit - f36 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f24 1
knit - f21 1
knit - f18 1
knit - f15 1
knit - f12 1
knit - f9 1
knit - f6 1
knit - f3 1
knit - f0 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2619 on yarn 1]
xfer b4 f4;return loops [2618 on yarn 1]
xfer b13 f13;return loops [2615 on yarn 1]
xfer b16 f16;return loops [2614 on yarn 1]
xfer b25 f25;return loops [2611 on yarn 1]
xfer b28 f28;return loops [2610 on yarn 1]
xfer b37 f37;return loops [2607 on yarn 1]
xfer b40 f40;return loops [2606 on yarn 1]
xfer b49 f49;return loops [2603 on yarn 1]
xfer b52 f52;return loops [2602 on yarn 1]
knit + f1 1
knit + f4 1
knit + b7 1
knit + b10 1
knit + f13 1
knit + f16 1
knit + b19 1
knit + b22 1
knit + f25 1
knit + f28 1
knit + b31 1
knit + b34 1
knit + f37 1
knit + f40 1
knit + b43 1
knit + b46 1
knit + f49 1
knit + f52 1
knit + b55 1
knit + b58 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2662 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2663 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2666 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2667 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2670 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2671 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2674 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2675 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2678 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2679 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit - b59 1
knit - b56 1
knit - b53 1
knit - b50 1
knit - b47 1
knit - b44 1
knit - b41 1
knit - b38 1
knit - b35 1
knit - b32 1
knit - b29 1
knit - b26 1
knit - b23 1
knit - b20 1
knit - b17 1
knit - b14 1
knit - b11 1
knit - b8 1
knit - b5 1
knit - b2 1
;Resetting to sheet s0:g3 of 3
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2660 on yarn 1] from s1 relative to s0
xfer f4 b4;peel loops [2661 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2662 on yarn 1] from s1 relative to s0
xfer f10 b10;peel loops [2663 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2664 on yarn 1] from s1 relative to s0
xfer f16 b16;peel loops [2665 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2666 on yarn 1] from s1 relative to s0
xfer f22 b22;peel loops [2667 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2668 on yarn 1] from s1 relative to s0
xfer f28 b28;peel loops [2669 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2670 on yarn 1] from s1 relative to s0
xfer f34 b34;peel loops [2671 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2672 on yarn 1] from s1 relative to s0
xfer f40 b40;peel loops [2673 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2674 on yarn 1] from s1 relative to s0
xfer f46 b46;peel loops [2675 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2676 on yarn 1] from s1 relative to s0
xfer f52 b52;peel loops [2677 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2678 on yarn 1] from s1 relative to s0
xfer f58 b58;peel loops [2679 on yarn 1] from s1 relative to s0
;Peel sheet 2 relative to 0
knit + f0 1
knit + f3 1
knit + f6 1
knit + f9 1
knit + f12 1
knit + f15 1
knit + f18 1
knit + f21 1
knit + f24 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f36 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f48 1
knit + f51 1
knit + f54 1
knit + f57 1
;Resetting to sheet s1:g3 of 3
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;Peel sheet 2 relative to 1
xfer b1 f1;return loops [2660 on yarn 1]
xfer b4 f4;return loops [2661 on yarn 1]
xfer b13 f13;return loops [2664 on yarn 1]
xfer b16 f16;return loops [2665 on yarn 1]
xfer b25 f25;return loops [2668 on yarn 1]
xfer b28 f28;return loops [2669 on yarn 1]
xfer b37 f37;return loops [2672 on yarn 1]
xfer b40 f40;return loops [2673 on yarn 1]
xfer b49 f49;return loops [2676 on yarn 1]
xfer b52 f52;return loops [2677 on yarn 1]
knit - b58 1
knit - b55 1
knit - f52 1
knit - f49 1
knit - b46 1
knit - b43 1
knit - f40 1
knit - f37 1
knit - b34 1
knit - b31 1
knit - f28 1
knit - f25 1
knit - b22 1
knit - b19 1
knit - f16 1
knit - f13 1
knit - b10 1
knit - b7 1
knit - f4 1
knit - f1 1
;Resetting to sheet s2:g3 of 3
;Peel sheet 0 relative to 2
;Peel sheet 1 relative to 2
xfer b7 f7;peel loops [2737 on yarn 1] from s1 relative to s2
xfer b10 f10;peel loops [2736 on yarn 1] from s1 relative to s2
xfer b19 f19;peel loops [2733 on yarn 1] from s1 relative to s2
xfer b22 f22;peel loops [2732 on yarn 1] from s1 relative to s2
xfer b31 f31;peel loops [2729 on yarn 1] from s1 relative to s2
xfer b34 f34;peel loops [2728 on yarn 1] from s1 relative to s2
xfer b43 f43;peel loops [2725 on yarn 1] from s1 relative to s2
xfer b46 f46;peel loops [2724 on yarn 1] from s1 relative to s2
xfer b55 f55;peel loops [2721 on yarn 1] from s1 relative to s2
xfer b58 f58;peel loops [2720 on yarn 1] from s1 relative to s2
;Peel sheet 2 relative to 2
knit + b2 1
knit + b5 1
knit + b8 1
knit + b11 1
knit + b14 1
knit + b17 1
knit + b20 1
knit + b23 1
knit + b26 1
knit + b29 1
knit + b32 1
knit + b35 1
knit + b38 1
knit + b41 1
knit + b44 1
knit + b47 1
knit + b50 1
knit + b53 1
knit + b56 1
knit + b59 1
outhook 1;Cutting active yarn on 1
