;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 15
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
;KS: Cast on 4loops from 0to 4
tuck - f3 1
tuck - f1 1
tuck + f0 1
tuck + f2 1
tuck - f3 1
tuck - f1 1
tuck + f0 1
tuck + f2 1
releasehook 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
outhook 1;Cutting active yarn on 1
